stages:
  data_ingestion:
    cmd: py -m src.repoRatePred.pipeline.stage_01_data_ingestion_pipeline
    deps:
      - src/repoRatePred/pipeline/stage_01_data_ingestion_pipeline.py
      - src/repoRatePred/components/data_ingestion.py
    params:
      - config/config.yaml:
        - data_ingestion
  data_validation:
    cmd: py -m src.repoRatePred.pipeline.stage_02_data_validation_pipeline
    deps:
      - src/repoRatePred/pipeline/stage_02_data_validation_pipeline.py
      - src/repoRatePred/components/data_validation.py
    params:
      - config/config.yaml:
        - data_validation
      - schema.yaml:
    outs:
      - artifacts/data_validation/status.txt
  data_transformation:
    cmd: py -m src.repoRatePred.pipeline.stage_03_data_transformation_pipeline
    deps:
      - src/repoRatePred/pipeline/stage_03_data_transformation_pipeline.py
      - src/repoRatePred/components/data_transformation.py
    params:
      - config/config.yaml:
        - data_transformation
      - schema.yaml:
        - targer_colunm
  data_training:
    cmd: py -m src.repoRatePred.pipeline.stage_04_data_training_pipeline
    deps: 
      - src/repoRatePred/pipeline/stage_04_data_training_pipeline.py
      - src/repoRatePred/components/data_trainer.py
    params:
      - config/config.yaml:
        - model_trainer
      - params.yaml:
        - model_trainer
    outs:
      - artifacts/model_trainer/model.pkl
  model_evaluation:
    cmd: py -m src.repoRatePred.pipeline.stage_05_data_evaluation_pipeline
    deps:
      - src/repoRatePred/pipeline/stage_05_data_evaluation_pipeline.py
      - src/repoRatePred/components/model_evaluation.py
    params:
      - config/config.yaml:
        - model_evaluation