stages:
  data_ingestion:
    cmd: py -m src.repoRatePred.pipeline.stage_01_data_ingestion_pipeline
    deps:
      - src/repoRatePred/pipeline/stage_01_data_ingestion_pipeline.py
      - src/repoRatePred/components/data_ingestion.py
    params:
      - config/config.yaml:
        - data_ingestion