model_trainer:
  params:
    Random Forest: 
      max_features: ['sqrt','log2']
      n_estimators: [4,8,16,32,64,128,256]
      max_depth : [3,5,7,9]
      n_jobs: [-1]
    Gradient Boosting :
      learning_rate: [.1,.01,.05,.001]
      subsample: [0.75,0.8,0.85,0.9]
      max_features: ['sqrt','log2']
      n_estimators: [32,64,128,256, 512]
      max_depth: [3,5,6]
    XGBRegressor:
      learning_rate: [.01,.05,.001]
      n_estimators: [32,64,128,256]
      max_depth: [3,5,10]
      n_jobs: [-1]
    AdaBoost Regressor: 
      learning_rate: [.1,.01,0.5,.001]
      n_estimators: [8,16,32,64,128,256]
    Elastic Net:
        alpha: [0.9, 1, 5]
        l1_ratio: [0.8,1]